POST http://{{host}}/api/commands/spatial.create_production_unit
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "shalasawdadawdawdh",
  "type": "FIELD",
  "area": {
    "unit": "HECTARE",
    "value": 3
  }
}

###

POST http://{{host}}/api/commands/spatial.configure_production_unit
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": "74e35fb1-9ad1-4acd-978e-db49fe47e741",
  "schema": {
    "beds": [
      {

        "id": "7d7f6ee8-6534-4b94-95d3-4db06a274e37",
        "type": "BLOCK",
        "x": 0.6,
        "y": 0.2,
        "width": 3,
        "length": 0.8,
        "name": "Грядка 1",
        "code": "B- 1"
      },
      {
        "id": "5a5d8d3d-7fcf-482e-9f86-34ca74f141cb",
        "type": "BLOCK",
        "x": 1.8,
        "y": 1.9,
        "width": 3,
        "length": 0.8,
        "name": "Грядка 2",
        "code": "B- 2"
      }
    ]
  }
}
###

POST http://localhost:8080/api/queries/spatial.list_production_units
Authorization: Bearer {{token}}
Content-Type: application/json

{}